version: '3.8'

services:

  jenkins:
    container_name: jenkins
    image: mborne/jenkins:lts
    build: .
    environment:
      - TZ=Europe/Paris
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      # allows external css
      - "JENKINS_JAVA_OPTS=-Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; style-src 'self' 'unsafe-inline';\""
    networks:
      - jenkins
      - devbox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.${HOST_HOSTNAME}`)"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    restart: unless-stopped

  jenkins-docker:
    container_name: docker
    image: docker:dind
    #command: ["--registry-mirror", "https://mirror.gcr.io"]
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs

networks:
  jenkins:
    name: jenkins
  devbox:
    name: devbox
    external: true
